### ISSUE TITLE
maven仓库不能正常导入

### ISSUE THREAD

**Issue by Neptunejiang** [wayn111/mybatis-xmlreload-spring-boot-starter#1]
![E8L{FEU690H(ZS0R6T __7H](https://user-images.githubusercontent.com/46320680/233237624-db238c0f-2d3b-4f2b-9cdf-03f53a3c6c28.png)
![(1T5G~3AT6 NBZ%P$6%_CE7](https://user-images.githubusercontent.com/46320680/233237638-1adb9650-d9c4-499a-8456-36dd4020431c.png)

**Comment by wayn111** [comment]
sorry, groupId忘了改了，正确地址：
```
<dependency>
    <groupId>io.github.wayn111</groupId>
    <artifactId>mybatis-xmlreload-spring-boot-starter</artifactId>
    <version>3.0.3.m1</version>
</dependency>
```

**Comment by Neptunejiang** [comment]
可以正常导入了，但是这项目是只能适配spring-boot集成mybatis吗，mybatis-plus或者jeecg-boot集成mybatis/mybatis-plus不支持吗。
![}OSZI@1ZGFJ`L2Z2LI NWZD](https://user-images.githubusercontent.com/46320680/233524263-c9326837-2116-4815-b845-2c339e31a256.png)
![U0E5(D0BK{506@OWQJ FMGM](https://user-images.githubusercontent.com/46320680/233524273-a3f9445c-a33c-4313-a0fc-23896f338a53.png)

![5Y @@W@E{9IC6ALRA@{5_WN](https://user-images.githubusercontent.com/46320680/233524276-0e832727-9866-4f10-988e-a78c1f31d6e3.png)
![(%MBJ2R~NW64G9UGNJF34O8](https://user-images.githubusercontent.com/46320680/233524282-559bd3cc-4e5c-425a-9d5f-fe0886a9157b.png)

**Comment by wayn111** [comment]
适配了mybatis plus 3.0，你可以试试

**Comment by Neptunejiang** [comment]
应该是的，我刚刚看了一些项目里mybatis-plus版本是3.4.1的。这边除了更换版本外还有别的方式适配吗。我技术有限，看了下源码没找到适配相关的东西😂

**Comment by wayn111** [comment]
我说错了，支持 mybatis-plus 3.0以上

**Comment by Neptunejiang** [comment]
那我上面改完xml之后重新build了控制台里输出的sql和xml里的还是不一样的

**Comment by wayn111** [comment]
你这边能加我微信吗 13617159841 我给你远程看下

**Comment by Neptunejiang** [comment]
这个不是个人的项目，我只是自己本地开发的时候想方便一些，反复重启有点影响开发效率😂

**Comment by wayn111** [comment]
哦哦，好吧，你可以贴下你的mybatis 版本，我回去看看

**Comment by wayn111** [comment]
我用jeecgboot复现了你说的问题，修改后可以使用，你可以使用下面这个版本

```xml
<dependency>
    <groupId>io.github.wayn111</groupId>
    <artifactId>mybatis-xmlreload-spring-boot-starter</artifactId>
    <version>3.0.3.m2</version>
</dependency>
```
刚推送，过半个小时，应该可以下载

**Comment by Neptunejiang** [comment]
<dependency>
            <groupId>io.github.wayn111</groupId>
            <artifactId>mybatis-xmlreload-spring-boot-starter</artifactId>
            <version>2.0.3.m2</version>
        </dependency>
这个版本不支持吗，我用3.0的好像有东西不兼容了，可能有别人改了什么配置

**Comment by wayn111** [comment]
你的项目如果是 SpringBoot2.0+ 版本的话，mybatis-xmlreload-spring-boot-starter 用 2.0.3.m2 这个版本应该是支持的，你看下控制台有报错吗，之前不能用是因为jeecgboot把xml文件放在java目录下，导致我没读取到，2.0.3.m2兼容了这个问题

**Comment by Neptunejiang** [comment]
![1682315772092](https://user-images.githubusercontent.com/46320680/233912179-ab261628-8926-437f-8a5b-9dfb26a0f26c.png)
![1682315980707](https://user-images.githubusercontent.com/46320680/233912185-4f68600e-3803-4186-bf92-4f7fc1fa3ec8.png)
启动没有报错，改完xml重新build之后没有起效果，也没有报错

**Comment by wayn111** [comment]
我在家测试过了是可以的，可能你的xml文件位置或者mybtis 版本有啥不一样

**Comment by Neptunejiang** [comment]
![F1KKCJY5KB_6{59_KPQ6W](https://user-images.githubusercontent.com/46320680/234184034-23680548-7041-49b3-9165-5c4f7c66c7ef.png)
![G%U8)S`MX0RBOHELS7EBLI9](https://user-images.githubusercontent.com/46320680/234184064-22e238cf-700c-49ab-8a86-cb906f851f63.png)
这是mybatis-plus的版本，和xml的位置。这个和子父级配置文件没有什么关系吧

**Comment by wayn111** [comment]
你用最新的3.0.3.m3试试把，不让远程，我也不知道你具体是本地啥情况，也不好帮你解决😂
```
<dependency>
    <groupId>io.github.wayn111</groupId>
    <artifactId>mybatis-xmlreload-spring-boot-starter</artifactId>
    <version>3.0.3.m3</version>
</dependency>
```

**Comment by Neptunejiang** [comment]
好的，我后面自己搞个简单的mybatis项目然后引用2.0试试，十分感谢

**Comment by wayn111** [comment]
> 好的，我后面自己搞个简单的mybatis项目然后引用2.0试试，十分感谢

不用2.0 用3.0就行了，我最新的3.0.3.m3提高了兼容性
