### ISSUE TITLE
不能直接使用在一些项目为何？

### ISSUE THREAD

**Issue by HayBranch** [wayn111/mybatis-xmlreload-spring-boot-starter#3]
![image](https://github.com/wayn111/mybatis-xmlreload-spring-boot-starter/assets/106044418/d9c1c242-fcd9-4b12-888c-773e1abc3aab)
tClass一直报错，改成了aClass

![image](https://github.com/wayn111/mybatis-xmlreload-spring-boot-starter/assets/106044418/01d143ba-b7e6-406a-9e7c-a04c9014a8be)
这个也报错
Error parsing Mapper XML. Cause: java.lang.IllegalArgumentException: Parameter Maps collection already contains value

**Comment by wayn111** [comment]
可以加我wx：waynaqua，我给你远程看看

**Comment by HayBranch** [comment]
![image](https://github.com/wayn111/mybatis-xmlreload-spring-boot-starter/assets/106044418/43502b60-12c1-411a-a71b-df17df709bc3)
在我需要使用的项目中加入了parameterMap，并且都用aClass后好像就可以使用了，只测试了select，有空再测测其他的

**Comment by HayBranch** [comment]
我将您的项目改动后存在了我的gitee私有仓库里做做备份哈

**Comment by HayBranch** [comment]
我好像用的springboot3.0的代码给我2.7.8的项目了 🤣

**Comment by HayBranch** [comment]
> 我好像用的springboot3.0的代码给我2.7.8的项目了 🤣

没看出来springboot2.0分支和main有啥区别。。。

**Comment by wayn111** [comment]
Spring Boot 升级3.0后，自动配置使用META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports ,而不是META-INF/spring.factories
