### ISSUE TITLE
<resultMap下有<association时保存会报错正常吗 

### ISSUE THREAD

**Issue by HayBranch** [wayn111/mybatis-xmlreload-spring-boot-starter#4]
![image](https://github.com/wayn111/mybatis-xmlreload-spring-boot-starter/assets/106044418/5812ccb5-e2b1-44b2-9f6b-08e46c4b05b6)
像这种！会报association已经存在

**Comment by wayn111** [comment]
已修复，可以更新至最新的 3.0.5.m3 或者 2.0.5.m3 版本试试
